project:
  type: website
  output-dir: docs 
website:
  title: "Mariam K. Garcia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: morph
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

