{
  "hash": "1761fc40c389c4a4e38ebfa387f6f313",
  "result": {
    "markdown": "---\ntitle: \"Historical Redlining and its Impact on Commmunities in LA \"\ndescription: \"Geospatial analysis on different HOLC graded areas\"\nauthor:\n  - name: Mariam Garcia\n    url: https://mariamkg00.github.io/\n    affiliation: Master of Environmental Data Science Program @ The Bren School (UCSB) \n    affiliation-url: https://ucsb-meds.github.io/ \nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\ndate: 12-12-2023\ncategories: [Quarto, R, MEDS, Geospatial] # self-defined categories\ncitation: \n  url: https://mariamkg00.github.io/blog/geospatial-analysis-of-HOLC-in-LA/ \n---\n\n\n## Background\n\nThis blog post aims to highlight the lasting effects of zoning, particularly in Los Angeles. The incorporation of HOLC (Homeowners Loan Corporation Act) has led to long lasting and detrimental effects in which economic security of minority communities was no longer deemed a possibility. The Federal Home Loan Bank Board (FHLBB) set standards in place to which neighborhood demographics (i.e percent of minority population) was deemed a factor in loan eligibility. Following the stock market crash and Great Depression, countless banks across the country began to close. According to the Urban History Association, \"as banks failed by the thousands, freezing credit markets and increasing unemployment, foreclosures skyrocketed and threatened to destroy the national housing industry\" (Woods 2012). In order to remediate mass daily foreclosures, Congress then put in place the Home Owners' Loan Corporation (HOLC) in order to help desperate homeowners. However, HOLC associated unsuitable candidates for a loan with their ethnic backgrounds, leaving many minority communities behind in moving forward from economic despair.\n\nCurrent ongoing cases of environmental injustices/racism are arguably consequences of prejudiced enforcement of the past. America's long history of racial segregation still has left its mark in Los Angeles. HOLC and their ranking systems were used to determine whether a certain neighborhood or region is suitable for a loan. Their ranking system, (A (green), B (blue), C (yellow), D (red)) was then used to block access to loans for home ownership, which is currently known as 'redlining'. However, redlined communities tend to have less greenery and are typically hotter than other neighborhoods/communities.\n\nIn this project, I aim to investigate whether or not redlined communities in Los Angeles have higher rates of pollution burden, have less reports of bird sightings as an indication of biodiversity.\n\n## Data Information\n\nTo obtain demographic and environmental data by census tract in Los Angeles, we will be using tdata from the **EPA's Environmental Justice Screening and Mapping Tool.**\n\nFor HOLC grade designations in Los Angeles, we will be using a GeoJSON file from the Digital Scholars Lab containing redlining information.\n\nLastly ,for biodiversity data represented by bird sightings, we will use data from the Global Biodiversity Information Facility.\n\nSince the data was too big to upload, I uploaded them into a zip folder which can be accessed [here]{.underline}.\n\n#### Investigating the Legacy of Redlining in Current Environmental Injustice\n\nLoading necessary packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tmap)\nlibrary(tidyverse)\nlibrary(sf)\nlibrary(spData)\nlibrary(here)\nlibrary(dplyr)\nlibrary(sp)\nlibrary(gt)\n```\n:::\n\n\nReading in EJScreen data and filter to Los Angeles County\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# reading in EJ Screen data\nejscreen <- st_read(\"data/EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `EJSCREEN_StatePctiles_with_AS_CNMI_GU_VI' from data source \n  `C:\\Users\\maria\\Documents\\git\\mariamkg00.github.io\\blog\\geospatial-analysis-of-HOLC-in-LA\\data\\EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb' \n  using driver `OpenFileGDB'\nSimple feature collection with 243021 features and 223 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -19951910 ymin: -1617130 xmax: 16259830 ymax: 11554350\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n:::\n\n```{.r .cell-code}\n# filtering to LA county \n\nla_county <- ejscreen %>% \n  filter(CNTY_NAME %in% c(\"Los Angeles County\"))\n```\n:::\n\n\nIn order to visualize waste water discharge by census block groups, I will use `tmap()` in order to help identify which census block groups are above the 95th percentile of waste water discharge while adding a centroid using `st_centroid()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# making centroids using st_centroid()\n\nla_ejscreen_centroids <- st_centroid(la_county) %>% \n  filter(P_PWDIS > 95)\n\n\n#using tmap to plot \ntm_shape(la_county)+\n  tm_fill(fill = 'PWDIS', palette = 'BuGn',\n              title = 'Wastewater Discharge')+\n  tm_shape(la_ejscreen_centroids)+\n  tm_dots(fill = 'red')+\n  tm_graticules()+\n  tm_compass()+\n  tm_layout(main.title = 'Map of Wastewater Discharge by Census Block Groups in LA County') +\n  tm_scale_bar(position = c(\"LEFT\",\"BOTTOM\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nDeprecated tmap v3 code detected. Code translated to v4\n```\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nIn order to find census block groups with less than 5% of the population is considered low income.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlow_income_lac <- la_county %>% \n  filter(LOWINCPCT < .05)\n\n#Calculating percentages based on the number of rows in each new subset. \nprint(nrow(low_income_lac)/nrow(la_county)* 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.114398\n```\n:::\n:::\n\n\nOf the total census block groups in Los Angeles County, only **6.11%** of census block groups have less than a 5% low income population.\n\nIn order to find percent of census block groups that are above the 80th percentile for PM 2.5 AND above the 80th percentile for Superfund proximity, we will use the `filter()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neighty_percentile_pm_sf <- la_county %>% \n  filter(P_PM25 > 80 & P_PNPL > 80) %>% \n  drop_na()\nprint(nrow(eighty_percentile_pm_sf)/nrow(la_county) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.03839\n```\n:::\n:::\n\n\nApproximately **17.03%** of census block groups in LA County are above the 80th percentile for Particulate Matter AND for Superfund proximity.\n\n#### Redlining\n\nI will use the `st_read()` function along with `st_make_valid()` in order to incorporate valid geometries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLA_redlining <- st_read(\"https://dsl.richmond.edu/panorama/redlining/static/citiesData/CALosAngeles1939/geojson.json\") %>%\n  st_make_valid()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `geojson' from data source \n  `https://dsl.richmond.edu/panorama/redlining/static/citiesData/CALosAngeles1939/geojson.json' \n  using driver `GeoJSON'\nSimple feature collection with 417 features and 14 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -118.6104 ymin: 33.70563 xmax: -117.7028 ymax: 34.30388\nGeodetic CRS:  WGS 84\n```\n:::\n:::\n\n\nIn order to make a map of historical redlining boundaries colored by HOLC grade, I will use `tm_shape()` along with making an associated color palette to distinguish different HOLC grades.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# making appropriate color palette for HOLC ranking system\nholc_grades <- c('#5DB271','#5D92B2','#ECDD29','#F14646')\ntm_shape(LA_redlining)+\n  tm_polygons(fill = 'grade', palette = holc_grades)+\n  tm_scale_bar()+\n  tm_compass()+\n  tm_graticules()+\n  tm_layout(main.title = 'Map of Historical Redlining Boundaries in LA County')+\ntm_shape(la_county)+\n  tm_borders(col_alpha = 0.5)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nIn order to find the number of census block groups that fall within areas with HOLC grades, I will use `st_within()`. The reason it is best to use `st_within()` is to\n\nBut first, I need to change the CRS of the Los Angeles EJ screen data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nla_county <- st_transform(la_county, crs = st_crs(LA_redlining))\n\nholc_groups_la <- st_join(la_county, LA_redlining, join = st_within, left = FALSE)\n\nprint(nrow(holc_groups_la))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 920\n```\n:::\n:::\n\n\nThere are **920 census block groups** that fall within areas with assigned HOLC grades in Los Angeles County.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}